---
groups:
  - name: master
    jobs:
      - hadolint
      - rubocop
      - rspec
      - build-test
      - testinfra
      - docker-build
      - major
      - minor
      - patch

  - name: testing
    jobs:
      - hadolint-branch
      - rubocop-branch
      - rspec-branch
      - build-test-branch
      - testinfra-branch

resource_types:
  - name: git-multibranch
    type: docker-image
    source:
      repository: ((nexus_ip)):((nexus_docker_port))/cfcommunity/git-multibranch-resource

resources:
  - name: resource-git
    type: git
    icon: github
    source:
      uri: https://github.com/Firebladee/docker_rspec.git
      branch: master

  - name: resource-git-branch
    type: git-multibranch
    source:
      uri: https://github.com/Firebladee/docker_rspec.git
      branches: '.*'
      ignore_branches:
        - master

  - name: docker-temp
    type: docker-image
    icon: docker
    source:
      repository: ((nexus_ip)):((nexus_docker_port))/testing
      username: admin
      password: admin123
      insecure_registries:
        - http://((nexus_ip)):((nexus_docker_port))

  - name: docker-build
    type: docker-image
    icon: docker
    source:
      repository: ((nexus_ip)):((nexus_docker_port))/fireblade/rspec

  - name: docker-libvirt
    type: registry-image
    icon: docker
    source:
      repository: ((nexus_ip)):((nexus_docker_group_port))/fireblade/libvirt

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:Firebladee/docker_rspec.git
      branch: version
      file: version
      initial_version: 0.0.1

jobs:
  - name: hadolint
    public: true
    plan:
      - get: resource-git
        trigger: true
      - get: docker-libvirt
        trigger: true
      - task: validate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/hadolint/hadolint
              tag: latest-debian
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                hadolint --config resource-git/.hadolint.yaml resource-git/Dockerfile

  - name: rubocop
    public: true
    plan:
      - get: resource-git
        trigger: true
      - get: docker-libvirt
        trigger: true
      - task: rubocop
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/ruby
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                cd resource-git
                gem install rubocop
                rubocop

  - name: rspec
    public: true
    plan:
      - get: resource-git
        trigger: true
        passed:
          - rubocop
      - task: rspec
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/fireblade/rspec
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                source /docker-lib.sh
                start_docker
                cd resource-git
                rake
        
  - name: build-test
    public: true
    plan:
      - get: resource-git
        passed:
          - hadolint
        trigger: true
      - put: docker-temp
        params:
          build: resource-git/

  - name: testinfra
    public: true
    plan:
      - get: resource-git
        passed:
          - build-test
          - rspec
        trigger: true
      - task: hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/testing
              username: admin
              password: admin123
              insecure_registries:
                - http://((nexus_ip)):((nexus_docker_group_port))
          run:
            path: echo
            args: ["Testinfra"]

  - name: docker-build
    public: true
    plan:
      - get: resource-git
        passed:
          - testinfra
        trigger: true
      - put: docker-build
        params:
          build: resource-git
      - put: version
        params:
          bump: patch

  - name: hadolint-branch
    public: true
    plan:
      - get: resource-git-branch
        trigger: true
      - get: docker-libvirt
        trigger: true
      - task: validate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/hadolint/hadolint
              tag: latest-debian
          inputs:
            - name: resource-git-branch
          run:
            path: sh
            args:
              - -exc
              - |
                hadolint --config resource-git-branch/.hadolint.yaml resource-git/Dockerfile

  - name: rubocop-branch
    public: true
    plan:
      - get: resource-git-branch
        trigger: true
      - get: docker-libvirt
        trigger: true
      - task: rubocop
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/ruby
          inputs:
            - name: resource-git-branch
          run:
            path: sh
            args:
              - -exc
              - |
                cd resource-git-branch
                gem install rubocop
                rubocop

  - name: rspec-branch
    public: true
    plan:
      - get: resource-git-branch
        trigger: true
        passed:
          - rubocop-branch
      - task: rspec
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/fireblade/rspec
          inputs:
            - name: resource-git-branch
          run:
            path: sh
            args:
              - -exc
              - |
                source /docker-lib.sh
                start_docker
                cd resource-git-branch
                rake

  - name: build-test-branch
    public: true
    plan:
      - get: resource-git-branch
        passed:
          - hadolint-branch
        trigger: true
      - put: docker-temp
        params:
          build: resource-git-branch/

  - name: testinfra-branch
    public: true
    plan:
      - get: resource-git-branch
        passed:
          - build-test-branch
          - rspec-branch
        trigger: true
      - task: hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/testing
              username: admin
              password: admin123
              insecure_registries:
                - http://((nexus_ip)):((nexus_docker_group_port))
          run:
            path: echo
            args: ["Testinfra"]

  - name: major
    public: true
    plan:
      - put: version
        params:
          bump: major

  - name: minor
    public: true
    plan:
      - put: version
        params:
          bump: minor

  - name: patch
    public: true
    plan:
      - put: version
        params:
          bump: patch
