pipeline:
  name: Docker_rspec
  identifier: Docker_rspec
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Fireblade
        repoName: docker_rspec
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: echo "Hello"
                  description: test
              - step:
                  type: Run
                  name: hadolint
                  identifier: hadolint
                  spec:
                    connectorRef: Dockerhub
                    image: hadolint/hadolint:latest-debian
                    shell: Sh
                    command: hadolint --config .hadolint.yaml Dockerfile
  delegateSelectors:
    - docker-delegate
